server:
  port: 90

#eureka:
#  client:
#    register-with-eureka: false
#    service-url:
spring:
  devtools:
    restart:
      enabled: true

#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/