server:
  port: 8003

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.zhaluo.box.api.entity           # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
  application:
    name: zhaluocloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://192.168.13.129:3306/cloud3                 # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
      validation-query: SELECT 1
      test-while-idle: false
      test-on-borrow: false
      test-on-return: false
#datasource:
#  name: era
#  url: jdbc:oracle:thin:@10.1.15.143:1521:orasdev
#  username: orasdev
#  password: acca1234
#  # 使用druid数据源
#  type: com.alibaba.druid.pool.DruidDataSource
#  driver-class-name: oracle.jdbc.OracleDriver
#  # 下面为连接池的补充设置，应用到上面所有数据源中
#  # 初始化大小，最小，最大
#  initialSize: 5
#  minIdle: 5
#  maxActive: 20
#  # 配置获取连接等待超时的时间
#  maxWait: 60000
#  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#  timeBetweenEvictionRunsMillis: 60000
#  # 配置一个连接在池中最小生存的时间，单位是毫秒
#  minEvictableIdleTimeMillis: 300000
#  validationQuery: SELECT 1 from dual
#  testWhileIdle: true
#  testOnBorrow: false
#  testOnReturn: false
#  # 打开PSCache，并且指定每个连接上PSCache的大小
#  poolPreparedStatements: true
#  maxPoolPreparedStatementPerConnectionSize: 20
#  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#  filters: stat,wall,log4j
#  # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#  # 合并多个DruidDataSource的监控数据
#  #useGlobalDataSourceStat: true
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #注册的三台服务器的地址.多台地址之间用 "逗号" 分割
      defaultZone: http://eureka7003.com:7003/eureka/

  instance:
    instance-id: zhaluocloud-dept8003
    prefer-ip-address: true    #访问路径可以显示当前ip

info:
  app.name: zhaluocloud
  company.name: www.box.zhaluo.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
 
