
server:
  port: 8004

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.zhaluo.box.api.entity           # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
  application:
    name: zhaluocloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/cloud4              # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
    #注册的多台服务器的地址.多台地址之间用 "逗号" 分割
      defaultZone: http://eureka7004.com:7004/eureka/,http://eureka7005.com:7005/eureka/,http://eureka7006.com:7006/eureka/
    registry-fetch-interval-seconds: 30  # 服务缓存清单更新时间

  #      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: ${project.artifactId}:${server.port}
    prefer-ip-address: true    #访问路径可以显示当前ip
    lease-expiration-duration-in-seconds: 90  #服务失效的时间
    lease-renewal-interval-in-seconds: 30  # 服务续约调用时间间隔

#
info:
  app.name: zhaluocloud
  company.name: www.box.zhaluo.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}

#  devtools:
#    restart:
#      enabled: true # 开启
#      additional-paths: src/main/java # 重启的目录

