server: 
  port: 3344 
  
spring:
  application:
    name:  zhaluocloud-config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:zhaluo-box/zhaluoCloud-Config.git #GitHub上面的git仓库名字
 

